# TODO: Cache both pnpm & cargo

name: 'Test'
on: 
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/pnpm/action-setup?tab=readme-ov-file#use-cache-to-reduce-installation-time
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        
      - name: Run actor-core tests
        run: pnpm test

      # - name: Install Rust
      #   uses: dtolnay/rust-toolchain@stable
      # - name: Run Rust client tests
      #   run: cd rust/client && cargo test

  # TODO: This is broken
  # test-cli:
  #   runs-on: ubuntu-latest
  #
  #   services:
  #     verdaccio:
  #       image: verdaccio/verdaccio:6
  #       ports:
  #         - 4873:4873
  #       options: --name verdaccio
  #
  #   steps:
  #       - uses: actions/checkout@v4
  #       - run: corepack enable
  #       # https://github.com/orgs/community/discussions/42127
  #       - run: /usr/bin/docker cp ${{ github.workspace }}/.verdaccio/conf/config.yaml verdaccio:/verdaccio/conf/config.yaml
  #       - run: /usr/bin/docker restart verdaccio
  #
  #       - uses: actions/cache@v4
  #         with: 
  #           path: .turbo
  #           key: ${{ runner.os }}-turbo-${{ github.sha }}
  #           restore-keys: |
  #             ${{ runner.os }}-turbo-
  #       - uses: actions/setup-node@v4
  #         with:
  #           node-version: '22.14'
  #           cache: 'yarn'
  #       - run: yarn install
  #       - run: yarn build
  #       - run: npm i -g tsx
  #       - run: ./scripts/e2e-publish.ts
  #       - run: yarn workspace @actor-core/cli run test
  #
